Bug fix for RomaniaProvider ignoring the LaunchYear property of the PublicHoliday
nager/Nager.Date pull request #185
Opened 2020-01-05 17:58 UTC by BalintBanyasz

This PR implements the missing launch year filter for Romania which caused incorrect results and also adds unit tests for multiple years.

2020-01-06 12:06 UTC, tinohager commented
Currently no provider filter by launch year. It is an optional value.

2020-01-06 19:41 UTC, BalintBanyasz commented
> Currently no provider filter by launch year. It is an optional value.

In that case, this is a more general issue.

I would expect that all functions that return holidays for a given date, year or date range, should always respect the launch year of the holidays, otherwise, the returned holidays may not be valid (like in case of Romania, Good Friday and Children's Day are incorrectly returned for years earlier than 2018 and 2017 respectively). Putting this filter right in the `Get(int year)` method seemed like right place to prevent any errors, even if accessed directly.

I understand that the LaunchYear is an optional parameter, but the condition `.Where(x => x.LaunchYear == null || x.LaunchYear <= year)` already respects this because it returns all holidays that don't have a launch year defined.

2020-01-06 19:44 UTC, tinohager commented
I think at the moment you can also filter the `LaunchYear` after the request. I will consider your proposal.

2020-01-06 20:25 UTC, BalintBanyasz commented
Sure, I understand that. The problem is that one would expect that getting the holidays for a specific year would use the rule set that was in effect for the given year. I can't think of a scenario where one would need the holidays that are in effect today to be projected to a past year where they did't exist.

2021-01-11 22:12 UTC, samtrion requested changes

2021-01-11 22:12 UTC, samtrion commented on README.md
> +| .NET | [ShaNetHoliday](https://github.com/Shaenn/ShaNetHoliday) | 63 |
Can you please provide a valid repository? This one is not available.

2021-01-12 18:47 UTC, BalintBanyasz commented on README.md
> +| .NET | [ShaNetHoliday](https://github.com/Shaenn/ShaNetHoliday) | 63 |
Hi @samtrion, it looks like the maintainer has decided to take down the repo (and the NuGet package has been unlisted as well). I couldn't find any forks or alternative repositories for the project, so it should be removed.

2022-09-19 19:07 UTC, closed without merging