Add local holidays in Korea
nager/Nager.Date pull request #237
Opened 2021-02-01 12:23 UTC by raculus

2021-02-01 19:54 UTC, tinohager reviewed
- Rename KoreaProvider to SouthKoreaProvider
- Add it to DateSystem

2021-02-01 21:02 UTC, samtrion requested changes

2021-02-01 21:02 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/KoreaProvider.cs
> +                var lunarNewYear3 = koreanCalendar.ToDateTime(year, this.MoveMonth(1, leapMonth), 2, 0, 0, 0, 0);
Isn't the following line much simpler? `var lunarNewYear3 = lunarNewYear2.AddDays(1)`

2021-02-01 21:02 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/KoreaProvider.cs
> +                var Chuseok1 = koreanCalendar.ToDateTime(year, this.MoveMonth(8, leapMonth), 14, 0, 0, 0, 0);   //Has alternative holidays
Please simplify Chuseok2 and Chuseok3, with `.AddDays(1)`

2021-02-01 21:02 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/KoreaProvider.cs
> +                var Chuseok1 = koreanCalendar.ToDateTime(year, this.MoveMonth(8, leapMonth), 14, 0, 0, 0, 0);   //Has alternative holidays
Please consider the notation of the variables

2021-02-02 06:12 UTC, raculus commented on Src/Nager.Date/PublicHolidays/KoreaProvider.cs
> +            items.Add(new PublicHoliday(year, 5, 5, "어린이날", "Children's Day", countryCode));    //Has alternative holidays
For Lunar New Year and Chuseok, if it overlaps with Sunday, the next non-public holiday will be set as a public holiday.
And for Children's Day, if it overlaps with Saturday or another holiday, the first non-public holiday following that day is a holiday.
[https://ko.wikipedia.org/wiki/%EB%8C%80%EC%B2%B4%ED%9C%B4%EC%9D%BC%EC%A0%9C%EB%8F%84#%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD](url)

2021-02-02 08:33 UTC, samtrion requested changes

2021-02-02 08:33 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/SouthKoreaProvider.cs
> +                while (lunarNewYear1.DayOfWeek == DayOfWeek.Sunday)
Please use the [`.Shift`](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/Extensions/DateTimeExtension.cs#L13) method, as in the [`JapanProvider`](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/JapanProvider.cs) example.

2021-02-02 08:33 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/SouthKoreaProvider.cs
> +                while (Chuseok1.DayOfWeek == DayOfWeek.Sunday)
Please use the [`.Shift`](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/Extensions/DateTimeExtension.cs#L13) method, as in the [`JapanProvider`](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/JapanProvider.cs) example.

2021-02-02 08:33 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/SouthKoreaProvider.cs
> +            while (childrenDay.DayOfWeek == DayOfWeek.Saturday || childrenDay.DayOfWeek == DayOfWeek.Sunday)
Please use the [`.Shift`](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/Extensions/DateTimeExtension.cs#L13) method, as in the [`JapanProvider`](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/JapanProvider.cs) example.

2021-02-02 11:19 UTC, samtrion requested changes

2021-02-02 11:19 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/SouthKoreaProvider.cs
> +                Chuseok1 = Chuseok1.Shift(sunday => sunday.AddDays(1), sunday => sunday.AddDays(1));
Hi, there seems to be a copy&paste error here. The first parameter deals with the shifting of Saturdays and the second parameter deals with the shifting of Sundays.

If I read it correctly from your previous commits, the correct wording would be.
```cs
var chuseok1 = koreanCalendar.ToDateTime(year, this.MoveMonth(8, leapMonth), 14, 0, 0, 0, 0);   //Has substitute holiday
chuseok1 = chuseok1 .Shift(saturday => saturday, sunday => sunday.AddDays(1));
var chuseok2 = chuseok1 .AddDays(+1).Shift(saturday => saturday, sunday=>sunday.AddDays(1));
var chuseok3 = chuseok1 .AddDays(+1).Shift(saturday => saturday, sunday=>sunday.AddDays(1));
```

2021-02-02 11:25 UTC, raculus commented on Src/Nager.Date/PublicHolidays/SouthKoreaProvider.cs
> +                Chuseok1 = Chuseok1.Shift(sunday => sunday.AddDays(1), sunday => sunday.AddDays(1));
Thank you for your advice.
I will fix it.

2021-02-02 11:26 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/SouthKoreaProvider.cs
> +                var lunarNewYear3 = lunarNewYear1.AddDays(-1).Shift(saturday => saturday, sunday => sunday.AddDays(1));
If Day 1 of the Lunar New Year is a Monday, then Day -1 would also be Monday. Here the shift is not correct.

2021-02-02 21:05 UTC, tinohager commented on Src/Nager.Date/PublicHolidays/SouthKoreaProvider.cs
> +                var koreanCalendar = new KoreanLunisolarCalendar();
```suggestion

            var koreanCalendar = new KoreanLunisolarCalendar();
            if (year >= koreanCalendar.MinSupportedDateTime.Year && year < koreanCalendar.MaxSupportedDateTime.Year)
            {
```

2021-02-02 21:17 UTC, tinohager commented
@raculus Thank you for helping us to add new countries we are very grateful for your support

2021-02-02 22:22 UTC, merged