Fix Costa Rica public holidays
nager/Nager.Date pull request #276
Opened 2021-05-07 01:24 UTC by parayacr

- Fix Costa Rica holidays
Cultures National Day no longer a holiday, it was replaced with the Army Abolition Day

- Fix names and add local names

2021-05-07 06:34 UTC, samtrion requested changes

2021-05-07 06:34 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
> -            items.Add(new PublicHoliday(year, 10, 12, "Cultures National Day", "Cultures National Day", countryCode));
Since we also try to meet historical holidays. I would ask you to also check here by condition whether this holiday is relevant for the year x. Instead of deleting the holiday completely from the project.

2021-05-07 06:34 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
> +            items.Add(new PublicHoliday(year, 12, 1, "Día de la Abolición del Ejército", "Army Abolition Day", countryCode));
Seit wann ist dieser Feiertag gülitg?

2021-05-07 06:34 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
> +            items.Add(new PublicHoliday(year, 5, 1, "Día Internacional del Trabajo", "Labour Day", countryCode));
Based on the [link](https://en.wikipedia.org/wiki/Public_holidays_in_Costa_Rica), Costa Rica also has a holiday shift. Can you send us this information as well? For this, please take a closer look at the [`.Shift()`](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/Extensions/DateTimeExtension.cs#L30-L52) method.

2021-05-08 14:17 UTC, parayacr commented on Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
> -            items.Add(new PublicHoliday(year, 10, 12, "Cultures National Day", "Cultures National Day", countryCode));
Yes, makes sense. Thank you.

2021-05-08 14:17 UTC, parayacr commented on Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
> +            items.Add(new PublicHoliday(year, 12, 1, "Día de la Abolición del Ejército", "Army Abolition Day", countryCode));
Is valid since 2020.

2021-05-08 14:17 UTC, parayacr commented on Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
> +            items.Add(new PublicHoliday(year, 5, 1, "Día Internacional del Trabajo", "Labour Day", countryCode));
Applied the corresponding shifts, thank you.

2021-05-10 07:23 UTC, samtrion commented
Is there a link for the law that is applied here? Preferably in English

2021-05-16 18:59 UTC, samtrion requested changes

2021-05-16 18:59 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/CostaRicaProvider.cs
> +            if ((exceptionYears == null || !exceptionYears.Contains(date.Year)) && applicableYears.Contains(date.Year))
If I understand correctly, there will only be shifts in holidays from 2020 to 2024. The logic used for this is far too complex and unnecessary.
Moreover, `ref` is used instead of a return value. Please rework again.

2021-06-01 21:44 UTC, samtrion approved these changes

2021-06-15 05:54 UTC, merged