Update issue templates
nager/Nager.Date pull request #281
Opened 2021-05-13 11:36 UTC by samtrion

2021-05-14 19:10 UTC, tinohager requested changes

2021-05-14 19:10 UTC, tinohager commented on .github/ISSUE_TEMPLATE/feature-request--country-support.md
> +---
please update the filename '--'

2021-05-14 19:10 UTC, tinohager commented on .github/ISSUE_TEMPLATE/feature-request--country-support.md
> +about: Suggest an country and information for this project
why `an`? 
Maybe `Suggest a country or information for this project`

2021-05-14 19:10 UTC, tinohager commented on .github/ISSUE_TEMPLATE/feature-request--country-support.md
> +    Please fill in the following questions as detailed as possible, so that we can directly ease the work.
Please fill out the following questions in as much detail as possible so that we can facilitate your work directly.
@HayriPV can you help us here?

2021-05-17 09:01 UTC, tinohager approved these changes

2021-05-17 10:48 UTC, HayriPV commented on .github/ISSUE_TEMPLATE/feature-request--country-support.md
> +    Please fill in the following questions as detailed as possible, so that we can directly ease the work.
Questions to ask to identify incorrect holidays.

Country?

2021-05-17 10:51 UTC, HayriPV commented on .github/ISSUE_TEMPLATE/feature-request--country-support.md
> +    Please fill in the following questions as detailed as possible, so that we can directly ease the work.
Questions to ask to identify incorrect holidays.

We could ask for the following information

Country
Public holiday name
Is this holiday missing or incorrect
If incorrect, please provide the correct date.

If missing, please provide the date
Is this an ongoing public holiday or a one-off

2021-08-11 09:31 UTC, merged