Add SingaporeProvider
nager/Nager.Date pull request #318
Opened 2021-08-15 02:07 UTC by YipingRuan

2021-08-15 08:00 UTC, samtrion requested changes

2021-08-15 08:00 UTC, samtrion commented on Src/Nager.Date/PublicHolidays/SingaporeProvider.cs
> +                "https://www.mom.gov.sg/employment-practices/public-holidays#Year-2022"
We try to at least support the last years and the next x years.

2021-08-15 08:01 UTC, samtrion requested changes

2021-08-15 08:01 UTC, samtrion commented on Src/Nager.Date.UnitTest/Country/SingaporeTest.cs
> +            Assert.AreEqual("New Year’s Day", publicHolidays[0].Name);
Please add more tests, especially for the years with optional holidays like 2022

2021-08-15 09:12 UTC, YipingRuan commented on Src/Nager.Date/PublicHolidays/SingaporeProvider.cs
> +                "https://www.mom.gov.sg/employment-practices/public-holidays#Year-2022"
Agree. Would be better is this is mentioned in the contribution guide.

2021-08-15 09:52 UTC, YipingRuan commented
https://github.com/nager/Nager.Date/issues/275

2021-08-15 17:51 UTC, tinohager commented
@YipingRuan Good Friday is a calculated holiday available via [ICatholicProvider](https://github.com/nager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/IsleOfManProvider.cs)

2021-08-29 02:07 UTC, YipingRuan commented on Src/Nager.Date/PublicHolidays/SingaporeProvider.cs
> +                var chineseCalendar = new ChineseLunisolarCalendar();
Can have more hint? I copied the code from https://github.com/nager/Nager.Date/blob/fc6de194942b1408439c4078089fa6d269cf1db7/Src/Nager.Date/PublicHolidays/SurinameProvider.cs#L59

2021-09-20 20:04 UTC, tinohager approved these changes

2021-09-20 20:05 UTC, merged