Fix CheckCounties test to not ignore providers without an ICountyProvider implementation.
nager/Nager.Date pull request #359
Opened 2021-12-15 03:35 UTC by Kermittt

Implement ICountyProvider for BosniaAndHerzegovina, France, NewZealand and UnitedStates.

2021-12-15 21:22 UTC, tinohager requested changes

2021-12-15 21:22 UTC, tinohager commented on src/Nager.Date.UnitTest/Common/CountryTest.cs
> +            if (failures.Length > 2)
I don't like the new unit test logic. A test for 2 makes little sense from my point of view

2021-12-15 21:22 UTC, tinohager commented on src/Nager.Date/PublicHolidays/FranceProvider.cs
> +        public IDictionary<string, string> GetCounties()
Add all counties https://www.iso.org/obp/ui/#iso:code:3166:FR

2021-12-15 21:22 UTC, tinohager commented on src/Nager.Date/PublicHolidays/NewZealandProvider.cs
> +                { "NZ-WTC", "West Coast" }
Missing (https://en.wikipedia.org/wiki/Regions_of_New_Zealand)
NZ-TAS

2021-12-16 04:01 UTC, Kermittt commented on src/Nager.Date.UnitTest/Common/CountryTest.cs
> +            if (failures.Length > 2)
The `2` refferred to the CR/LF that was being appended to the initial StringBuilder.  This did make the result a bit vague.  Have switched to a list to clarify the intent, with the string formatting done later.

2021-12-16 04:05 UTC, Kermittt commented on src/Nager.Date/PublicHolidays/FranceProvider.cs
> +        public IDictionary<string, string> GetCounties()
It's generally unclear from existing examples whether GetCounties should return a definitive list, or only needs to include Counties that actually have holidays defined.  We are only interested in the latter, and since it can sometimes be unclear exactly what should be included without local knowledge, I added only the necessary ones.
I'ave attempted to add the remainder, but France appears to be one of those complex ones so I'm not entirely sure it all makes sense.

2021-12-16 04:05 UTC, Kermittt commented on src/Nager.Date/PublicHolidays/NewZealandProvider.cs
> +                { "NZ-WTC", "West Coast" }
Reasons as above.  Have completed the list.

2022-05-23 01:53 UTC, Kermittt commented
@tinohager
[Kermittt](https://github.com/Kermittt) requested a review from [tinohager](https://github.com/tinohager) [5 months ago](https://github.com/nager/Nager.Date/pull/359#event-5775713305)

Requested changes have been made some time ago.  Could we please have this PR approved?  We have a live system which needs the update.

2023-02-21 20:04 UTC, tinohager commented
@Kermittt Sorry for the late feedback I have adopted the changes

2023-02-21 20:04 UTC, closed without merging